

CREATE TABLE "projects" (
"id_project" INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
"project_name" TEXT
, "project_shortname" text NULL, "project_version" text NULL);


CREATE TABLE "changelogs" (
"id_changelog" INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
"id_project" INTEGER NOT NULL ON CONFLICT ROLLBACK,
"id_user" INTEGER NOT NULL ON CONFLICT ROLLBACK,
"date" TEXT,
"sent" INTEGER DEFAULT 1,
"changelog_text" TEXT NOT NULL ON CONFLICT ROLLBACK
);


CREATE TABLE "users_projects" (
"id_user_project" INTEGER PRIMARY KEY ON CONFLICT ROLLBACK AUTOINCREMENT,
"id_user" INTEGER NOT NULL ON CONFLICT ROLLBACK,
"id_project" INTEGER NOT NULL ON CONFLICT ROLLBACK
);


CREATE TABLE "users" (
"id_user" INTEGER PRIMARY KEY ASC ON CONFLICT ROLLBACK AUTOINCREMENT,
"name" TEXT NOT NULL ON CONFLICT ROLLBACK,
"email" TEXT NOT NULL ON CONFLICT ROLLBACK UNIQUE ON CONFLICT ROLLBACK,
"password" TEXT,
"login" TEXT UNIQUE ON CONFLICT ROLLBACK,
"admin" INTEGER DEFAULT 0
);


-- 